[versions]
accompanistSystemuicontroller = "0.34.0"
activityComposeVersion = "1.10.1"
agp = "8.7.3"
androidxMaterial = "1.8.2"
androidxMaterialVersion = "1.8.2"
#androidxNavigationCompose = "2.7.0"
converterGson = "2.9.0"
coreKtxVersion = "1.16.0"
firebaseBom = "33.14.0"
foundation = "1.8.2"
gson = "2.10.1"
kotlin = "2.0.0"
coreKtx = "1.16.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
kotlinxCoroutinesAndroid = "1.9.0"
kotlinxCoroutinesPlayServices = "1.9.0"
lifecycleRuntimeKtx = "2.9.0"
activityCompose = "1.10.1"
composeBom = "2025.05.01"
appcompat = "1.7.0"
lifecycleRuntimeKtxVersion = "2.9.0"
mapsCompose = "6.4.1"
material = "1.12.0"
activity = "1.10.1"
constraintlayout = "2.2.1"
material3 = "1.3.2"
materialVersion = "1.8.2"
navigationCompose = "2.9.0"
places = "4.2.0"
placesVersion = "4.2.0"
playServicesMapsVersion = "19.2.0"
protoliteWellKnownTypes = "18.0.1"
gms="4.4.2"
firebase-messaging = "24.1.1"

retrofit = "2.9.0"
scribejavaApis = "8.3.3"
ui = "1.8.2"
uiToolingPreview = "1.8.2"
uiVersion = "1.8.2"
volley = "1.2.1"

[libraries]
accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanistSystemuicontroller" }
androidx-activity-compose-v180 = { module = "androidx.activity:activity-compose", version.ref = "activityComposeVersion" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-core-ktx-v1120 = { module = "androidx.core:core-ktx", version.ref = "coreKtxVersion" }
androidx-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "foundation" }
androidx-lifecycle-runtime-ktx-v262 = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtxVersion" }
androidx-material = { module = "androidx.compose.material:material", version.ref = "materialVersion" }
androidx-material-v100 = { module = "androidx.compose.material:material", version.ref = "androidxMaterialVersion" }
androidx-material-v177 = { module = "androidx.compose.material:material", version.ref = "androidxMaterial" }
androidx-material3-v131 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
#androidx-navigation-compose-v270 = { module = "androidx.navigation:navigation-compose", version.ref = "androidxNavigationCompose" }
androidx-ui-v177 = { module = "androidx.compose.ui:ui", version.ref = "uiVersion" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "converterGson" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-database-ktx = { module = "com.google.firebase:firebase-database-ktx" }
firebase-installations-ktx = { module = "com.google.firebase:firebase-installations-ktx" }
firebase-messaging-ktx = { module = "com.google.firebase:firebase-messaging-ktx" , version.ref = "firebase-messaging"}
gms-play-services-maps = { module = "com.google.android.gms:play-services-maps", version.ref = "playServicesMapsVersion" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3", version = "1.3.2" } # or latest stable

androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesAndroid" }
kotlinx-coroutines-play-services = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services", version.ref = "kotlinxCoroutinesPlayServices" }
maps-compose = { module = "com.google.maps.android:maps-compose", version.ref = "mapsCompose" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
places = { group = "com.google.android.libraries.places", name = "places", version.ref = "places" }
places-v310 = { module = "com.google.android.libraries.places:places", version.ref = "placesVersion" }
protolite-well-known-types = { group = "com.google.firebase", name = "protolite-well-known-types", version.ref = "protoliteWellKnownTypes" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
scribejava-apis = { module = "com.github.scribejava:scribejava-apis", version.ref = "scribejavaApis" }
ui = { module = "androidx.compose.ui:ui", version.ref = "ui" }
ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "uiToolingPreview" }
volley = { module = "com.android.volley:volley", version.ref = "volley" }
#firebase_messaging_ktx = { group = "com.google.firebase", name = "firebase-messaging-ktx", version.ref = "firebase-messaging" }
#androidx_navigation_compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation-compose" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
google-gms = { id = "com.google.gms.google-services", version.ref = "gms" } # ✅ Add this

